### PR TITLE
Add 'kexec' reboot method as alternative

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by thkukuk** [comment]
Thanks for the patch, but I'm not happy about how the option was implemented, I think it will create wrong expactations:
"transactional-update dup salt --kexec"

What would a customer expect from this? That salt is using kexec for reboot? Most likely, while I doubt they expect the machine will reboot immeaditly with kexec.

I would either make it configurable only via transactional-update.conf, so that a "transactional-update reboot" will use kexec, or make this option depending on the "systemctl reboot" case.

And adjusting the manual page is missing.

**Comment by okurz** [comment]
Right, does not make sense as an option like this. I also thought about putting it into https://github.com/SUSE/rebootmgr . Maybe that makes more sense after all?

**Comment by thkukuk** [comment]
On Mon, May 28, Oliver Kurz wrote:

> Right, does not make sense as an option like this. I also thought about putting
> it into https://github.com/SUSE/rebootmgr . Maybe that makes more sense after
> all?

If, then this should be additional. Having this for users who
call transactional-update and want to reboot directly, kexec could
also be nice.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & CaaSP
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by okurz** [comment]
@laenion thanks for merging. I think it should not give any problems but please see https://github.com/openSUSE/transactional-update/pull/15#issuecomment-392441506 which I agree with as a point for improvement. If you want to move forward following these ideas feel free to change my code contributions accordingly. Not sure I would find the time soon to do it properly.

**Comment by laenion** [comment]
@okurz: All problems from the comment should not occur with the extended commit: By not making it a runtime option the reboot method is selected via configuration file. If the salt command is given the reboot method will always be overwritten with `salt`. I've also adjusted the manpage by adding a short description of the new option.

**Pull request merged**
