### PR TITLE
Fix syntax error

### PR DESCRIPTION
**Pull request by aafeijoo-suse**

### CODE REVIEW

**Review by aplanas — APPROVED** [review]

**Comment by laenion** [comment]
Thanks!

**Comment by aafeijoo-suse** [comment]
You're welcome! I can help you to set up something like https://github.com/systemd/systemd/blob/main/.github/workflows/differential-shellcheck.yml if you want, it's useful to detect shell errors like this in the future.

**Comment by aplanas** [comment]
maybe we can progress in https://github.com/openSUSE/transactional-update/pull/120

**Comment by aafeijoo-suse** [comment]
> maybe we can progress in #120

The good thing about differential shellcheck is that it only performs shellcheck on modified code in a PR, i.e., it detects new errors before merging. Fixing current project-wide shellcheck warnings is not that easy :)

**Pull request merged**
