### PR TITLE
use new snapper for setting default and read-only

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by Vogtinator** [comment]
AFAIK one goal is to keep it compatible with supported SLE versions so this might need the old way as fallback

**Comment by lnussel** [comment]
up to Ignaz to go wild then :)

**Comment by lnussel** [comment]
ping? :)

**Comment by laenion** [comment]
Thanks a lot for triggering the snapper changes. I'll add the new snapper version dependency into the rpm spec file, let's hope these changes don't have to be backported into older releases.

(Merged manually due to indentation errors.)

**Pull request closed without merging**
