### PR TITLE
Enable FIPS and SELinux for sdboot

### LINKED ISSUE #113: use /etc/kernel/cmdline when using sdboot
for configuring selinux, transactional-update hardcodes grub stuff. Needs to use /etc/kernel/cmdline if sdboot is used though

### PR DESCRIPTION
**Pull request by danyspin97**
When running on a sdboot, modify /etc/kernel/cmdline instead of the grub config.

Fixes #113

### CODE REVIEW

**Comment by danyspin97** [comment]
This doesn't fix Grub with BLS yet, I am currently looking into that.

**Comment by aplanas** [comment]
> This doesn't fix Grub with BLS yet, I am currently looking into that.

Needs to be tested, but grub2-bls should also work with this change in /etc/kernel/cmdline, as the entry is created by sdbootutil the same for any boot loader (minus some checks related with the entry name)

**Comment by laenion** [comment]
So would it work if - instead of checking for an sdboot system explicitly - both _/etc/default/grub_ and _/etc/kernel/cmdline_ would just be changed _if_ they are present? Or mustn't _/etc/default/grub_ be changed any more when using GRUB2 with BLS?

**Comment by aplanas** [comment]
grub2-bls and systemd-boot under sdbootutil only requires changes in /etc/kernel/cmdline. sdbootutil is agnostic of the boot loaders as far as it is BLS

So, no, from grub2-bls no change in /etc/default/grub will make sense

**Comment by laenion** [comment]
That would mean the differentiator shouldn't be _/boot/efi/EFI/systemd/installed_by_sdbootutil_ as in the current patch, but it should check for and modify _/etc/kernel/cmdline_ instead, and _/etc/default/grub_ otherwise, correct?

**Comment by aplanas** [comment]
Better differentiator is /etc/kernel/cmdline, right? In BLS some agent will create the boot entries. For us is sdbootutil, but this can be a transient status.

This agent will use /etc/kernel/cmdline also, as sdbootutil is doing. So IMHO if [ -f /etc/kernel/cmdline ]; then update this file, else update /etc/default/grub

**Comment by aplanas** [comment]
I just remembered, perl-Bootloader can also touch and reference the /etc/kernel/cmdline and the boot entries.

**Comment by laenion** [comment]
Perfect - thanks a lot!

**Pull request merged**
